log4r_config:
   loggers:
      - name: default
        level: DEBUG
        outputters:
           - file
           - stdout
   outputters:
      - type: StdoutOutputter
        name: stdout
        formatter: *formatter
      - type: FileOutputter
        name: file
        filename: "log/app.log"
        formatter: *formatter

formatter: &formatter
   date_pattern: '%Y-%m-%d %H:%M:%S'
   pattern: '%d %l: %m'
   type: PatternFormatter
